### PR TITLE
Fixed #52 : Add a FAQ section

### LINKED ISSUE #52: [FEATURE] Add a FAQ section
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

_No response_

### Feature Description: FAQ Section

**Overview**:  
The proposed FAQ (Frequently Asked Questions) section will serve as a comprehensive resource for visitors interested in the rich culture, traditions, and attractions of Uttarakhand. This section aims to provide clear and concise answers to common inquiries, enhancing user engagement and improving overall site usability.

**Key Components**:

1. **Cultural Insights**: Address common questions about Uttarakhand's festivals, cuisine, folk art, and traditions, helping visitors gain a deeper understanding of the region.

2. **Travel Information**: Provide practical information for travelers, including best times to visit, travel tips, and local transportation options.

3. **Collapsible Format**: Use a collapsible layout for questions and answers to ensure the section is user-friendly and visually appealing.

### Screenshots

_No response_

### Would you like to work on this feature?

Yes

### Implementation Plan

**Implementation Plan**:
- Compile a list of frequently asked questions based on user interactions and feedback.
- Design the layout for the FAQ section to ensure clarity and ease of navigation.
- Develop the necessary front-end functionality to support the display of questions and answers.
- Test the FAQ section for usability before launching it on the site.

Hey @ajaynegi45 Please assign this task to me with label "gssoc-ext", "hacktoberfest-accepted" and "level3"

### PR DESCRIPTION
**Pull request by samyak-aditya**
Fixed #52 

#### Overview
This pull request introduces a new FAQ section to our Next.js application, enhancing the user experience by providing easily accessible information about our services. The update aims to clarify common inquiries and promote user engagement through improved design elements.

#### Key Changes

1. **New FAQ Section**:
   - Implemented a comprehensive FAQ section that includes five relevant questions and detailed answers. This addition helps users quickly find information about our services, addressing key areas of interest and concern.

5. **CSS Adjustments**:
   - Made necessary CSS updates to ensure proper alignment and spacing for the FAQ items and icons, contributing to a polished and user-friendly layout.

6. **Contact Section Addition**:
   - Added a dedicated section at the end of the FAQ that features a medium-sized image and a "Contact Us" button. This provides users with a clear way to reach out for additional assistance if their questions remain unanswered.
   
##Screenshot
Screenshot 2024-10-04 230527
Screenshot 2024-10-04 230546

#### Benefits
- **Enhanced User Experience**: The new FAQ section provides users with immediate access to important information, reducing uncertainty and enhancing their overall experience.
- **Visual Appeal**: The use of custom icons and a structured layout makes the FAQ section more engaging, encouraging users to explore the content.
- **Improved Clarity**: By addressing common questions directly, we help users better understand our services and encourage deeper engagement with the platform.

Please review the changes and share any feedback or suggestions for further improvements. Thank you!

### CODE REVIEW

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @samyak-aditya,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Make it responsive.
   Screenshot 2024-10-05 at 1 02 30 AM
   
 - Currently the text size and button is very large make it small. 
 - Improve the overall design.
 - use this [icon](https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/blob/main/public/chat.svg)

Once again, thank you for your contribution! ❤️

**Comment by samyak-aditya** [comment]
Hey @ajaynegi45 okay Let me Fix that and make it responsive

**Comment by samyak-aditya** [comment]
Hey @ajaynegi45 I am working on this 
I will push the updates in evening

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45 I am working on this I will push the updates in evening

Take your time to complete it; there's no need to worry. 

I'm currently managing several projects participating in Hacktoberfest and GSSoC, which means I receive multiple pull requests daily. This has made tracking reviewed PRs a bit challenging. Typically, I close PRs after reviewing them. Please don't worry about it – simply make the necessary changes and submit a new PR. If everything looks good, I'll ensure it gets merged.

Thank you for your understanding!

**Pull request closed without merging**
