### PR TITLE
added dynamic signup

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello
I have added the dynamic validation feature in signup page you told about
Pls check

### CODE REVIEW

**Comment by Prabal-verma** [comment]
i have reviewed this @ajaynegi45

**Comment by ajaynegi45** [comment]
> i have reviewed this @ajaynegi45

What review you have done..?

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @ ,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Add hide and show icon not text and align it well.
- When password field is active then show only.

   Screenshot 2024-10-18 at 1 39 36 PM


Once again, thank you for your contribution! ❤️

**Comment by ajaynegi45** [comment]
> Hello I have added the dynamic validation feature in signup page you told about Pls check

**Comment by Gauravtb2253** [comment]
should I create new PR after changes

**Pull request closed without merging**
