### PR TITLE
Added Filtering Functionality and new locations to Trekking page

### LINKED ISSUE #221: [FEATURE] Add Filtering Option for Trekking Locations
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

We need to implement a filtering option on the trekking page to enhance user experience. This feature will allow users to filter trekking locations based on various criteria such as difficulty level, district, and altitude 

### Feature Description

- Users can filter trekking locations by:
  - **Difficulty Level**: Easy, Medium, Hard
  - **District**:  The location of Trek
  - **Altitude**:  The height of trek
- The filter options should be clearly visible and accessible on the trekking page.
- The list of trekking locations updates dynamically based on the selected filters.
- Ensure that the filtering works seamlessly with existing features.

### Screenshots

_No response_

### Would you like to work on this feature?

Yes

### Implementation Plan

_No response_

### PR DESCRIPTION
**Pull request by IkkiOcean**
#### Description
This PR introduces the ability to filter treks based on difficulty level, district, and altitude in the Trekking component. Additionally, it implements a "not available" message to inform users when no treks match the selected filters. This enhancement significantly improves the user experience by providing clear feedback and functionality.

#### Changes Made
- **Filter Functionality**: 
  - Implemented filtering logic that allows users to filter treks based on:
    - **Difficulty Level**: Options include EASY, EASY TO MODERATE, MODERATE, MODERATE TO DIFFICULT, DEMANDING, and HIGH RISK.
    - **District**: Dynamically generated list of unique districts from the trek data.
    - **Altitude**: Options for Low, Moderate, and High based on altitude ranges.

- **"Not Available" Message**: 
  - Added a div that displays the message "No treks available based on your filters. Please adjust your selections." when no treks match the filters.
  - Ensured the message is styled for visibility and centered within the card container.
- Added content for the following treks:
  - Chandrashila Trek (Moderate, 4000 m, Rudraprayag)
  - Kedarkantha Trek (Easy to Moderate, 3810 m, Uttarkashi)
  - Nag Tibba Trek (Easy, 3022 m, Tehri Garhwal)
  - Roopkund Trek (Moderate, 5029 m, Chamoli)
  - Kalindi Khal Trek (Difficult, 5950 m, Chamoli)
  - Tarsar Marsar Trek (Moderate, 4000 m, Anantnag)

### Screenshot 

Screenshot 2024-10-27 at 4 31 57 PM

#### Video

https://github.com/user-attachments/assets/bab29d3f-7208-4773-bca3-0bfc77cd7201

#### Related Issues
- Closes #221

### CODE REVIEW

**Comment by IkkiOcean** [comment]
I add all the location I could find, and made the filter option design what it used to look like.

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @IkkiOcean,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- There is no district name Kumaon. 
   
    Screenshot 2024-10-27 at 10 58 54 PM

- Don't Dynamically generated list of district. Just add all present district name. As it was earlier.
- Don't add too much difficulty level. Only the three are best. Make simple and easy for user.
- The added trek are the best treks. Add more trek, make it goto guide for trekers
- Add google maps location link there. So that user can find best routes from there place
- Add more info about that trek like history or any story etc. Tell something interesting about that trek. Add eye catching info in outer paragraph so that user click it. I think remove the overview part and add all that info in outer para and if there is so long info then add it inside but without overview heading

   Screenshot 2024-10-27 at 11 07 46 PM

- Make one more section that if there is need of any special permission or registeration for that trek then add that process and all permission required and links etc.
- You haven't star the repo. Star the repo 🌟 to help us grow

Once again, thank you for your contribution! ❤️

**Comment by IkkiOcean** [comment]
@ajaynegi45  hey, I completed some of the changes you asked for.
- I made the level choice to only three i.e easy, moderate and difficult  
- I listed the district as it was earlier and filter will work using that.

As my this issue was about the filter but I still added some trek sites on your demand. I wanna work on the other features you mentioned but in a different issue as those deviates from the problems mentioned in the issue.

- regarding location, I have already raised and has been assign for the feature of adding map to location button, and Im working on that, I will raise the PR soon for it.
- About adding more details and information about the trekking location, as I have already said before its not a good idea adding more data to website without proper implementation of a database, but I can do it in a separate issue if you want but I would recommend setting up a database, which I can also help in.
- I starred the repo, im sorry for not doing it till now, as It slipped my mind.

My request is that you merge this PR so that I can move forward with development of map because I dont wanna cause merge conflicts.

**Review by ajaynegi45 — APPROVED** [review]
Hi @IkkiOcean,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by ajaynegi45** [comment]
> Hi @IkkiOcean,
> 
> Thank you for your prompt work on this issue. I appreciate your dedication to the project.
> 
> I have reviewed your work, and I need some changes.
> 
> * There is no district name Kumaon.
>     Screenshot 2024-10-27 at 10 58 54 PM
> * Don't Dynamically generated list of district. Just add all present district name. As it was earlier.
> * Don't add too much difficulty level. Only the three are best. Make simple and easy for user.
> * The added trek are the best treks. Add more trek, make it goto guide for trekers
> * Add google maps location link there. So that user can find best routes from there place
> * Add more info about that trek like history or any story etc. Tell something interesting about that trek. Add eye catching info in outer paragraph so that user click it. I think remove the overview part and add all that info in outer para and if there is so long info then add it inside but without overview heading
>    Screenshot 2024-10-27 at 11 07 46 PM
> * Make one more section that if there is need of any special permission or registeration for that trek then add that process and all permission required and links etc.
> * You haven't star the repo. Star the repo 🌟 to help us grow
> 
> Once again, thank you for your contribution! ❤️

Implement these issue in future pr

**Pull request merged**
