### PR TITLE
fix #34:  Implement Login and Signup Functionality

### LINKED ISSUE #34: [FEATURE] Implement Login and Signup Functionality (Frontend & Backend)
### Is this feature already requested?

- [x] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

Develop and integrate a secure **Login**, **Signup**, and **OTP** verification feature, ensuring smooth user experience and secure authentication. This feature will involve both frontend UI design and backend API development, along with OTP verification for account signup.

### Design Resources:
- <a href="https://www.figma.com/design/o82aPjIzHairrkqhem3S1Q/New-UI?node-id=252-38&t=pnd9LeK6OUwhckbh-1" target="_blank">Figma Design</a>
- <a href="https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/tree/main/Design" target="_blank">PDF Design</a>

#### Frontend:
- **UI Design** for the **Login**, **Signup**, and **OTP Verification** forms.
- **Required fields**:
  - **Signup**: 
    - Username
    - Name
    - Email
    - Password
    - Confirm Password
    - Checkbox: "Get Upcoming Uttarakhand Festival & Fair Alerts!"
    - OTP input field (shown after submitting signup form)
  - **Login**:
    - Email or Username
    - Password
- **OTP Flow**:
  - After successful submission of the **Signup** form, the user should receive an OTP via email.
  - The user should enter the OTP on the verification screen to complete the signup process.
- **Input validation** (real-time feedback as the user types):
  - Password must meet the following criteria:
    - Minimum 8 characters.
    - At least one uppercase letter (A-Z).
    - At least one lowercase letter (a-z).
    - At least one number (0-9).
    - At least one special character (!, @, #, $, etc.).
  - Password confirmation should match the entered password.
  - Username should be unique.
  - OTP should be a 6-digit numeric code.
- **Error/success messaging**:
  - Display appropriate messages for password validation, OTP verification, and form submission status.
- **Responsiveness**: Ensure the design adapts seamlessly across various devices and screen sizes.
- **Post-Login/Signup**:
  - On successful signup and OTP verification, redirect the user to the homepage.
  - Replace the "Login" button with a profile icon once the user is authenticated.

#### Backend:
- **API Endpoints**:
  - **POST** `/api/auth/signup`: Handles user registration and sends OTP via email.
  - **POST** `/api/auth/verify-otp`: Verifies the OTP and completes the signup process.
  - **POST** `/api/auth/login`: Handles user login.
- **OTP Flow**:
  - Upon user registration, generate a 6-digit OTP and send it via email.
  - Store OTP securely and associate it with the user for validation.
  - OTP should expire after a set time (e.g., 10 minutes).
- **Security**:
  - Securely store passwords using hashing (e.g., bcrypt).
  - Implement JWT-based authentication to maintain secure user sessions.
  - Ensure secure handling of OTP codes, including expiration and prevention of brute-force attacks.
  - Return appropriate status codes and messages for successful or failed operations.

  
### Additional Considerations:
- Implement unit and integration tests for both the frontend and backend.
- Ensure robust error handling on both frontend and backend (e.g., invalid credentials, OTP mismatch, server issues).
- Use environment variables to store sensitive information (e.g., JWT secret, email service credentials).
  
### Acceptance Criteria:
- Users can sign up with valid credentials and complete signup by entering the correct OTP.
- Users should receive dynamic error messages for invalid input, OTP mismatches, or expired OTPs.
- Successful login should create a persistent session using JWT tokens.
- Secure coding and authentication practices are followed, including OTP expiration.

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
- As directed in #34 
- Implementation is using

1.  Authjs
2. Drizzle ORM
3. Raw CSS
4. Responsive
5. more...

Demo Video

https://github.com/user-attachments/assets/dc2c15f8-919a-4f40-b0d7-c44262e91515

### CODE REVIEW

**Comment by ajaynegi45** [comment]
> @ajaynegi45 hope you like this PR. Let me know if their is any change required. Loved to contribute for Uttarakhand as I live near

The demo video is not playing. Also guide me on how to set up the database and other configurations

**Comment by priyanshuverma-dev** [comment]
@ajaynegi45 There are following steps to setup postgres.

1. Create a project on [Neon Tech](https://neon.tech/)

2. Create a database and copy the database URL.

3. Paste this URL in `.env` file
```
DATABASE_URL=<>
AUTH_SECRET=<>
RESEND_API_KEY=<>
RESEND_EMAIL=<>
```

4. SAME FOR RESEND.

5. Create a auth secret for next-auth

**Comment by ajaynegi45** [comment]
> Demo Video:
> https://screenrec.com/share/gES04ojNGY

The demo video is not playing
https://screenrec.com/share/gES04ojNGY

**Comment by priyanshuverma-dev** [comment]
@ajaynegi45 Here is the demo:

https://github.com/user-attachments/assets/dc2c15f8-919a-4f40-b0d7-c44262e91515

**Comment by ajaynegi45** [comment]
> @ajaynegi45 Here is the demo:
> 
>  uttrakhand-culture-feat-auth-demo.mp4

- Can you use [Sonner](https://sonner.emilkowal.ski) library for message.

**Comment by priyanshuverma-dev** [comment]
@ajaynegi45 Let me see as of my last everything was working. I will notify you after a fix

**Comment by ajaynegi45** [comment]
> Let me see as of my last everything was working. I will notify you after a fix

also implement these 
- Can you use [Sonner](https://sonner.emilkowal.ski/) library for message.
- For sending e-mail can you use nodemailer

**Pull request closed without merging**
