### PR TITLE
Done some enhancements and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
I have done all the enhancements and also added some new sections.

Enhancements I have done :-

1) Enhanced the project structure
2) Added need help with the basics section
3) Added project structure section
4) Added additional method of contributing through GitHub desktop section
5) Added good coding practices section
6) Added the help and support section
7) Add the pull request section

Fixes:[#168 ]
Closes:[#168 ]

image

image

image

image

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have done all the enhancements. Please check it once.

**Comment by milansamuel609** [comment]
Please check the changes once. If they are ok please kindly merge the PR.

**Comment by milansamuel609** [comment]
Please kindly merge my PR if all the changes are fine. Also please attach the label for gssoc ext and level

**Comment by milansamuel609** [comment]
Please kindly merge my PR of everything done is fine. Also please add the gssoc extend and level label

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @ ,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- In First Pull Request section add all points which was earlier.
- `For Help And Support 💬` and `Feedback and Support 🎗️` Both are same. Merge them into `Feedback and Support 🎗️`

Once again, thank you for your contribution! ❤️

**Pull request closed without merging**
