### PR TITLE
[FEAT] Added Map to "View Location" on Trekking Page

### LINKED ISSUE #169: Implement "View Location" Modal with Map on Trekking Page
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, there is no functionality on the trekking page that allows users to view the specific geographic locations of trekking spots. This missing feature limits the user's ability to visualize the treks and plan their trips accordingly. Adding a map modal will enhance the user experience by providing crucial location information.

### Feature Description

Implement a "View Location" modal on the trekking page that displays a map for each trekking location. The modal will open upon clicking a "View Location" button on the trekking card, showing the exact location of the trek. The map will be interactive, allowing users to zoom in, zoom out, and pan to explore the surrounding area.

### Screenshots

_No response_

### Would you like to work on this feature?

Yes

### Implementation Plan

I can use leaflet js to implement it or any other map api which you would recommend

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Overview
This PR introduces a Map component to the trekking page of the Uttarakhand website. The modal allows users to view the location of trekking destinations on a Mapbox map, enhancing user experience by providing an interactive geographical context.

### Changes Made
- **Added MapModal Component**: Created a new `MapModal.js` component that displays a Mapbox map centered on the specified location of the trekking site.
- **Map Modal CSS**: Implemented CSS styles in `MapModal.module.css` to ensure the map occupies the full modal space and maintains responsiveness.
- **Updated TrekCard Component**: Integrated the `MapModal` in the `TrekCard` component, enabling users to open the modal and view the location associated with each trek.
- **Map Configuration**: Configured Mapbox with appropriate access token and map settings, including zoom level and location markers.

### Implementation Details

- The modal opens when the "VIEW LOCATION" button is clicked within trekking page
- The map is centered on the location of start of trek , ensuring accurate representation.
- The modal includes a close button to exit the map view easily.

### Screenshots

https://github.com/user-attachments/assets/be920de5-f6f9-4a40-a8d3-f8252e0f2103
### Related Issues
- Closes #169 

### Additional Notes
- Make sure to set the environment variable `NEXT_PUBLIC_MAPBOX_TOKEN` with your Mapbox access token for the map to function correctly.
- This enhancement aims to improve user interaction and accessibility to trekking locations in Uttarakhand.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
- My Issue was about adding map to the view location button on trekking page. I have added coordinates of starting of trek to the map so that it helps the viewers.

- If there are any other things which you want me to add to the website, do tell me as I can raise new issues for them.

happy to contribute :)

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @ ,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- How to generate NEXT_PUBLIC_MAPBOX_TOKEN
- Add googlemap and applemap button above close button. So that when user click on it, It will open and show fastest route from there location.

Once again, thank you for your contribution! ❤️

**Comment by IkkiOcean** [comment]
> Hi @IkkiOcean,
> 
> Thank you for your prompt work on this issue. I appreciate your dedication to the project.
> 
> I have reviewed your work, and I need some changes.
> 
> * How to generate NEXT_PUBLIC_MAPBOX_TOKEN
> * Add googlemap and applemap button above close button. So that when user click on it, It will open and show fastest route from there location.
> 
> Once again, thank you for your contribution! ❤️

okay. I will make the changes right away in this same pr

**Comment by IkkiOcean** [comment]
@ajaynegi45 
https://github.com/user-attachments/assets/d1e4a031-385d-4321-b550-b0dc95028260

How to make Mapbox token:

To generate a Mapbox token, follow these steps:

1. **Sign Up / Log In**:
   - Go to [Mapbox](https://account.mapbox.com/auth/signup/) and sign up for an account or log in if you already have one.

2. **Navigate to Tokens**:
   - Once logged in, go to your [Account Tokens page](https://account.mapbox.com/access-tokens/).

3. **Create a New Token**:
   - Click on **Create a token**.
   - You can customize the token permissions, such as restricting access to specific Mapbox APIs or setting a domain restriction to limit where the token can be used.

4. **Name the Token**:
   - Give your token a meaningful name, especially if you plan to use multiple tokens for different applications or environments.

5. **Generate the Token**:
   - After configuring, click **Create token**. Your token will appear on the page.

6. **Copy and Use the Token**:
   - Copy the token and add it to your environment variables in your project, such as in a `.env` file:
     ```bash
     NEXT_PUBLIC_MAPBOX_TOKEN=your_generated_token_here
     ```

7. **Restart the Development Server**:
   - If you added the token to `.env`, restart your server to load the new environment variable. 

Your Mapbox token should now be active and ready to use in your application.

**Comment by ajaynegi45** [comment]
> @ajaynegi45
> 
>  maops.mp4 
> How to make Mapbox token:
> 
> To generate a Mapbox token, follow these steps:
> 
> 1. **Sign Up / Log In**:
>    
>    * Go to [Mapbox](https://account.mapbox.com/auth/signup/) and sign up for an account or log in if you already have one.
> 2. **Navigate to Tokens**:
>    
>    * Once logged in, go to your [Account Tokens page](https://account.mapbox.com/access-tokens/).
> 3. **Create a New Token**:
>    
>    * Click on **Create a token**.
>    * You can customize the token permissions, such as restricting access to specific Mapbox APIs or setting a domain restriction to limit where the token can be used.
> 4. **Name the Token**:
>    
>    * Give your token a meaningful name, especially if you plan to use multiple tokens for different applications or environments.
> 5. **Generate the Token**:
>    
>    * After configuring, click **Create token**. Your token will appear on the page.
> 6. **Copy and Use the Token**:
>    
>    * Copy the token and add it to your environment variables in your project, such as in a `.env` file:
>      ```shell
>      NEXT_PUBLIC_MAPBOX_TOKEN=your_generated_token_here
>      ```
> 7. **Restart the Development Server**:
>    
>    * If you added the token to `.env`, restart your server to load the new environment variable.
> 
> Your Mapbox token should now be active and ready to use in your application.

In mapbox it is asking for credit card

**Comment by ajaynegi45** [comment]
> @ajaynegi45
> 
>  maops.mp4 
> How to make Mapbox token:
> 
> To generate a Mapbox token, follow these steps:
> 
> 1. **Sign Up / Log In**:
>    
>    * Go to [Mapbox](https://account.mapbox.com/auth/signup/) and sign up for an account or log in if you already have one.
> 2. **Navigate to Tokens**:
>    
>    * Once logged in, go to your [Account Tokens page](https://account.mapbox.com/access-tokens/).
> 3. **Create a New Token**:
>    
>    * Click on **Create a token**.
>    * You can customize the token permissions, such as restricting access to specific Mapbox APIs or setting a domain restriction to limit where the token can be used.
> 4. **Name the Token**:
>    
>    * Give your token a meaningful name, especially if you plan to use multiple tokens for different applications or environments.
> 5. **Generate the Token**:
>    
>    * After configuring, click **Create token**. Your token will appear on the page.
> 6. **Copy and Use the Token**:
>    
>    * Copy the token and add it to your environment variables in your project, such as in a `.env` file:
>      ```shell
>      NEXT_PUBLIC_MAPBOX_TOKEN=your_generated_token_here
>      ```
> 7. **Restart the Development Server**:
>    
>    * If you added the token to `.env`, restart your server to load the new environment variable.
> 
> Your Mapbox token should now be active and ready to use in your application.

Create button like close.

**Comment by IkkiOcean** [comment]
@ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public

**Comment by ajaynegi45** [comment]
> @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there

Share it on LinkedIn

**Comment by ajaynegi45** [comment]
> @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there

Means UI part like close button

**Comment by IkkiOcean** [comment]
> > @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there
> 
> Share it on LinkedIn

sure. accept my request there.

**Comment by ajaynegi45** [comment]
> @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there


Something Like this with logo of each map
Screenshot 2024-10-30 at 1 59 33 PM

**Comment by IkkiOcean** [comment]
> > @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there
> 
> Something Like this with logo of each map Screenshot 2024-10-30 at 1 59 33 PM

oh okay

**Comment by ajaynegi45** [comment]
> > > @ajaynegi45 yeah most of map services require that for verification. I can send you mine but please keep it hidden as it might exceed the free quota if launched public. ans wht do you mean by close button. its already there
> > 
> > 
> > Something Like this with logo of each map Screenshot 2024-10-30 at 1 59 33 PM
> 
> oh okay


Logo like this
Screenshot 2024-10-30 at 2 01 00 PM

**Comment by IkkiOcean** [comment]
Screenshot 2024-10-30 at 2 25 39 PM
@ajaynegi45 done

**Comment by ajaynegi45** [comment]
> Screenshot 2024-10-30 at 2 25 39 PM @ajaynegi45 done
> accept my LinkedIn request, as I cant message you rn.

Accepted

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @IkkiOcean,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Not Responsive for mobile devices. Make it responsvie for 320px mobile also.
   
   Screenshot 2024-10-30 at 6 11 37 PM


Once again, thank you for your contribution! ❤️

**Comment by IkkiOcean** [comment]
@ajaynegi45 made it mobile responsive please check and merge. I am going to raise a new issue for adding more content so please mention the list of new content you want.


https://github.com/user-attachments/assets/7055694e-cb3e-400b-9fdf-436996e27970

**Comment by ajaynegi45** [comment]
> @ajaynegi45 made it mobile responsive please check and merge. I am going to raise a new issue for adding more content so please mention the list of new content you want.
> 
>  WhatsApp.Video.2024-10-31.at.05.43.43.mp4

I think the located location are not correct in map

**Comment by IkkiOcean** [comment]
> > @ajaynegi45 made it mobile responsive please check and merge. I am going to raise a new issue for adding more content so please mention the list of new content you want.
> > WhatsApp.Video.2024-10-31.at.05.43.43.mp4
> 
> I think the located location are not correct in map

they are starting location of the trek gathered from google

**Pull request merged**
