### PR TITLE
feat: Google Maps button issue no.#220

### PR DESCRIPTION
**Pull request by AE-Hertz**
The button opens directly google maps and directly goes to uttarakhand in satellite mode to show the greenry and helps in maintaining the meaning of the heritage.

accept this under hacktoberfest and gssoc-ext labels.

thank you.

### CODE REVIEW

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Not match with the goal of project. checkout this https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/149

**Comment by AE-Hertz** [comment]
@ajaynegi45 hey I delivered the feature as I mentioned in my issue no. #220 , keeping everything in mind. Then why this PR will not be merged?

**Comment by ajaynegi45** [comment]
> @ajaynegi45 hey I delivered the feature as I mentioned in my issue no. #220 , keeping everything in mind. Then why this PR will not be merged?
> 
> As I clearly stated everything in my issue, what and how I will be making and now you saying it's not matching goal of the project after I spend time on it.
> 
> If their is any issue I can solve, but please don't let my work goes invein.

We appreciate your efforts, but this feature wasn't quite what we had in mind. Could you revisit the idea? 

Checkout this https://github.com/ajaynegi45/Uttarakhand-Culture-NewUI/issues/149

**Comment by AE-Hertz** [comment]
@ajaynegi45 yes I read that and idea is preety good. But eventually a button will be needed and so that my button component can be easily integrated with 149 feat idea.

As gssoc about to end it felt bad as I spent lot of time on this and recieved nothing in return.(Or if you are comfortable I will PR to another branch)

Well thank you. Happy to contribute.

**Pull request closed without merging**
