### PR TITLE
Google Sign-In functionality

### PR DESCRIPTION
**Pull request by meghanakn473**
added the google sign in feature to the login page to help users to login easily

https://github.com/user-attachments/assets/74b0fedc-fe92-46aa-84f4-b322ff21b84d

### CODE REVIEW

**Comment by meghanakn473** [comment]
@ajaynegi45 please review and allow merge
and kindly assign labels

**Comment by meghanakn473** [comment]
@ajaynegi45 please update

**Comment by meghanakn473** [comment]
@ajaynegi45 ??

**Review by MastanSayyad — APPROVED** [review]

**Review by ajaynegi45 — COMMENTED** [review]
Hi @meghanakn473,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Resolve these error.

at JSON.parse (<anonymous>)
at O (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94083) {
  digest: '754964660'
}
Error occurred prerendering page "/auth". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at 3602 (/vercel/path0/.next/server/app/auth/page.js:1:2572)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at 9325 (/vercel/path0/.next/server/app/auth/page.js:1:133339)
    at Object.t [as require] (/vercel/path0/.next/server/webpack-runtime.js:1:143)
    at require (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18490)
    at I (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94362)
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:96668
    at F._fromJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:97106)
    at JSON.parse (<anonymous>)
    at O (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94083)
   Generating static pages (12/16) 
 ✓ Generating static pages (16/16)
 Export encountered errors on following paths:
	/auth/page: /auth
Error: Command "npm run build" exited with 1




Once again, thank you for your contribution! ❤️

**Comment by ajaynegi45** [comment]
@MastanSayyad who said you to merge it

**Pull request merged**
