### PR TITLE
Made Newsletter Functional

### LINKED ISSUE #49: Correcting the Join the Newsletter option
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

The Join the Newsletter option is not responding as its not even taking user input!

### Steps to Reproduce

_No response_

### Screenshots

Screenshot 2024-10-03 085615

### Would you like to work on this issue?

Yes

### Implementation Plan

_No response_

### PR DESCRIPTION
**Pull request by RiteshS1**
Fixed #49 

The Newsletter now sends a welcome mail to the subscribed users!

I have deployed my improved version for testing check it out at [](url) https://uttarakhand-culture-new-ui-ritesh.vercel.app/

You'll just have to add environment variables at the time of your deployment as ;

SMTP_USER=your@gmail.com
SMTP_PASSWORD=your-password

To test it locally just create a .env.local file and add the passwords there.

The mail can be further customized as per your requirements!

Let me know if there's something to improve on...

### CODE REVIEW

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @RiteshS1,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Replace the text 'Submitting' with a circular loading icon.

   Screenshot 2024-10-04 at 6 10 04 PM 

   https://github.com/user-attachments/assets/04ca8040-bdc4-4703-a33e-33c6d9e90598


- Remove the highlighted text and use [Sonner](https://sonner.emilkowal.ski) library for message.
    Screenshot 2024-10-04 at 6 09 38 PM






Once again, thank you for your contribution! ❤️

**Comment by RiteshS1** [comment]
Hei @ajaynegi45 ; I would have worked upon those suggestions but why did u close this pr w/o assigning any labels?

**Comment by RiteshS1** [comment]
Also regarding your query to retrieve mails; well there are more than one ways to do so like using MongoDB or GoogleSheets or even a JSON to store the entered mails; depends on the need.

**Comment by ajaynegi45** [comment]
> Hei @ajaynegi45 ; I would have worked upon those suggestions but why did u close this pr w/o assigning any labels?

Hi @RiteshS1, 
I'm currently managing several projects that are participating in Hacktoberfest and GSSoC, which means I'm receiving multiple pull requests daily. This has made it a bit challenging to track which ones I've reviewed. I usually close PRs that I have checked, and it seems yours was also closed. Please don't worry about it—just make the necessary changes and submit a new PR. If everything looks good, I'll make sure to merge it.

Thanks for your understanding!

**Comment by ajaynegi45** [comment]
> Also regarding your query to retrieve mails; well there are more than one ways to do so like using MongoDB or GoogleSheets or even a JSON to store the entered mails; depends on the need.

Which one is better according to you.

**Pull request closed without merging**
