### PR TITLE
Feature/update file structure

### PR DESCRIPTION
**Pull request by banasmita24**
Closses #211 
I have updated the File Structure.md file. Please do check and let me know if i need to change anything.
Thank you :)

### CODE REVIEW

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @banasmita24,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Not like that
- Previous format was correct but you haven't add description

Once again, thank you for your contribution! ❤️

**Comment by banasmita24** [comment]
@ajaynegi45 sorry, I didn't get you. Where should i add the description??

**Comment by banasmita24** [comment]
@ajaynegi45 pls do check now. Did u mean this?

**Comment by ajaynegi45** [comment]
> @ajaynegi45 pls do check now. Did u mean this?

Now write each file and folder description in front of them

**Pull request closed without merging**
