### PR TITLE
Upgraded Trekking Content with image and added functionality to read more

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Summary:
This PR enhances the tourist location cards on the **Uttarakhand Tourism** website by adding more detailed information and implementing a fully functional "Read More" button for improved user interaction.

### Changes:
1. **Upgraded Tourist Location Cards:**
   - Added more detailed information to the location cards, including:
     - **Routes** to reach the tourist spots.
     - **Nearby attractions** that can be explored.
     - **Recommended Gear:** 
     - **Physical challenges**
     - **Cultural Insights**
     - **Best Time to Visit**
     - **Image**
   - This provides tourists with richer, more informative content directly on the cards.

2. **"Read More" Button Implementation:**
   - The **"Read More" button** is now functional.
   - On click, the card expands to show the extra details like routes and nearby attractions, allowing users to explore additional information without leaving the page.

3. **Created a Separate Data Dictionary:**
   - Developed a **new dictionary** to store all the expanded information, keeping the code clean and maintainable.
   - This separation of data improves organization and facilitates easier updates or additions in the future.

### Affected Areas:
- Tourist location cards on the trekking page.
- Data management for tourist spots and attractions.
- UI interactions related to the "Read More" button.

### Linked Issues:
- Closes : #158

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@ajaynegi45 fixed the css of button

https://github.com/user-attachments/assets/99bb02a1-88f1-4a7c-b69c-2348b84c4fe5

**Review by ajaynegi45 — CHANGES_REQUESTED** [review]
Hi @IkkiOcean,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I need some changes.

- Not same as earlier. Make the UI part as earlier as it was.
   
   
    Screenshot 2024-10-24 at 8 38 50 PM


Once again, thank you for your contribution! ❤️

**Comment by IkkiOcean** [comment]
@ajaynegi45 can you clarify. the UI looks similar to me, previously read more button lost its effect on hover so I did corrected it in my latest PR. What do you mean by "make ui part as it was earlier" ? I'm happy to collaborate but before I commit to more changes I need to understand your vision properly.

**Comment by ajaynegi45** [comment]
> @ajaynegi45 can you clarify. the UI looks similar to me, previously read more button lost its effect on hover so I did corrected it in my latest PR. What do you mean by "make ui part as it was earlier" ? I'm happy to collaborate but before I commit to more changes I need to understand your vision properly.

Hover effect is present in earlier UI. checkout https://uttarakhand-culture.vercel.app/trekking and make paragraph text black color. readmore side line is missing. Just copy paste code from github main branch.

**Pull request closed without merging**
