### PR TITLE
Upgraded Trekking Content with image and added functionality to read more 

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Summary:
This PR enhances the tourist location cards on the **Uttarakhand Tourism** website by adding more detailed information and implementing a fully functional "Read More" button for improved user interaction.

### Changes:
1. **Upgraded Tourist Location Cards:**
   - Added more detailed information to the location cards, including:
     - **Routes** to reach the tourist spots.
     - **Nearby attractions** that can be explored.
     - **Recommended Gear:** 
     - **Physical challenges**
     - **Cultural Insights**
     - **Best Time to Visit**
     - **Image**
   - This provides tourists with richer, more informative content directly on the cards.

2. **"Read More" Button Implementation:**
   - The **"Read More" button** is now functional.
   - On click, the card expands to show the extra details like routes and nearby attractions, allowing users to explore additional information without leaving the page.

3. **Created a Separate Data Dictionary:**
   - Developed a **new dictionary** to store all the expanded information, keeping the code clean and maintainable.
   - This separation of data improves organization and facilitates easier updates or additions in the future.

### Video

https://github.com/user-attachments/assets/c9c7bcb1-f6cb-4c8e-bf0c-f1e9a856bca1

### Affected Areas:
- Tourist location cards on the trekking page.
- Data management for tourist spots and attractions.
- UI interactions related to the "Read More" button.

### Linked Issues:
- Closes : #158

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@ajaynegi45 Added image and fixed the card ui as you asked. This Pr has almost reached 700+ line of codes so I request you to let me add filter functionality in another issue. regards.

**Comment by IkkiOcean** [comment]
@ajaynegi45 why did you close it?? I wanted to move forward with further development. please merge it and add tags.

**Comment by ajaynegi45** [comment]
> @ajaynegi45 why did you close it?? I wanted to move forward with further development. please merge it and add tags.

when you make the changes, create new pr

**Comment by IkkiOcean** [comment]
@ajaynegi45 sir I told you I will develop it further in next issue since this one already has reached 700 Line of codes. once you merge the branch, I can move forward with the next commits. as you can see I have made read more function and added content with their own images which my issue was about. I wanna add functionality of filter and more content in the next issue. So please first merge this so I can move forward

**Comment by ajaynegi45** [comment]
> @ajaynegi45 sir I told you I will develop it further in next issue since this one already has reached 700 Line of codes. once you merge the branch, I can move forward with the next commits. as you can see I have made read more function and added content with their own images which my issue was about. I wanna add functionality of filter and more content in the next issue. So please first merge this so I can move forward

The changes you have to do is make readmore text as it was ealier.

**Comment by IkkiOcean** [comment]
what do you mean by "text as earlier"? like the font or you want to me remove the functionality of drop down which is happening right now when you click read more. I haven't changed the font tho

**Comment by ajaynegi45** [comment]
> what do you mean by "text as earlier"? like the font or you want to me remove the functionality of drop down which is happening right now when you click read more. I haven't changed the font tho

Only css part not the functionality

**Comment by IkkiOcean** [comment]
@ajaynegi45 sir then you can open this PR and I can implement the required changes  in the same pr. as I remember I didnt change the css of the button but I will look into it

**Pull request closed without merging**
